CREATE TABLE IF NOT EXISTS `carro` (
	`codigo` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`marca` VARCHAR(100) NOT NULL,
	`modelo` VARCHAR(100) NOT NULL,
	`placa` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`codigo`) USING BTREE
) ;